### ISSUE TITLE
line 117

### ISSUE THREAD

**Issue by ArcturusMajere** [asussman52/hotspot_comparison#1]
#select specific columns for output
gstat.hs<-gstat.hs[,c(1,3:5,15,18:20,25)]

Is this too many columns?

**Comment by asussman52** [comment]
You are correct; thank you for pointing out this problem! The shapefile was missing several data columns needed for the models. Somehow I mixed up the final file for the upload/archive, but I've replaced the shapefile and it should run smoothly now. Please let me know if you still have a problem. Thanks again!
